name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # GITHUB_TOKEN에 릴리즈 생성 권한 부여

jobs:
  build:
    name: Build and Package Projects
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies for C++
      run: sudo apt-get update && sudo apt-get install -y build-essential g++

    - name: Build C++ files
      run: |
        mkdir -p build/cpp
        for file in $(find homework4/design_pattern/cpp -name "*.cpp"); do
          g++ $file -o build/cpp/$(basename $file .cpp)
        done

    - name: Install Mono for C#
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Build C# files
      run: |
        mkdir -p build/csharp
        for file in $(find homework4/design_pattern/csharp -name "*.cs"); do
          mcs $file -out:build/csharp/$(basename $file .cs).exe
        done

    - name: Set up Kotlin
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Build Kotlin files
      run: |
        mkdir -p build/kotlin
        for file in $(find homework4/design_pattern/kotlin -name "*.kt"); do
          kotlinc $file -include-runtime -d build/kotlin/$(basename $file .kt).jar
        done

    - name: Create release package
      run: |
        mkdir -p release
        zip -r release/homework4_builds.zip build  # 수정: build 디렉터리를 압축
        ls -l release  # 디버깅: release 디렉터리 내용 출력

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: homework4_builds
        path: release/homework4_builds.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: homework4_builds
        path: release/homework4_builds.zip

    - name: Verify artifact exists
      run: |
        ls -l release  # 디버깅: release 디렉터리 내용 출력
        if [ ! -f release/homework4_builds.zip ]; then
          echo "Error: release/homework4_builds.zip not found"
          exit 1
        fi

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Release and Upload Files
      run: |
        gh release create v1.0.${{ github.run_number }} release/homework4_builds.zip \
          --title "Homework4 Build Release" \
          --notes "This release contains the compiled binaries for the C++, C#, and Kotlin projects."